[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_program = "82X9jUhf5wT8n3RvnDDhh7wYtPJPwTqFLUWTgaGLWkts"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./dependencies/wallet/test_user.json"
# wallet = "/home/nomadic/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "dependencies/deploy/token_program.so"

[[test.genesis]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
program = "dependencies/deploy/associated_token_account_program.so"
